// This file is generated by Prismic local builder. Update with care!

export { default as CodeSnippet } from "./CodeSnippet";
export { default as Image } from "./Image";
export { default as RichText } from "./RichText";
